title: "7 Days to Die Servers"
description: "Конфигурации и документация для серверов 7 Days to Die"

# GitHub Pages настройки
url: "https://your-username.github.io"
baseurl: "/7d2d-servers"

# Настройки Jekyll
markdown: kramdown
highlighter: rouge
theme: minima

# Плагины
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Исключения
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

# Настройки коллекций
collections:
  configs:
    output: true
    permalink: /:collection/:name/

# Значения по умолчанию
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "configs"
    values:
      layout: "config"

# SEO настройки
lang: ru
author:
  name: "Your Name"
  email: "your.email@example.com"

# Социальные ссылки
github_username: your-username

# Google Analytics (опционально)
# google_analytics: UA-XXXXXXXXX-X
